# 문제 2. 부산항 컨테이너 성장에서 환적의 기여 구조 파악

- 전체 컨테이너 물동량의 변화
- 수출입 물동량
- 환적 물동량

- 원본 파일명:부산광역시_부산항 물동량 현황

In [3]:
import pandas as pd 
import numpy as np

In [4]:
FILENAME = 'cargovolume.csv'
DATA_FILE_PATH = './cargovolume.csv'

In [13]:
origin = pd.read_csv(
    DATA_FILE_PATH, encoding='cp949')

In [14]:
## 데이터 확인
origin.head()

     연도   컨물동량   증감율  수출입소계    수입    수출   환적소계  환적점유율  환적증감율
0  2013  17686  3.75   8934  4424  4509   8748  49.47   7.38
1  2014  18683  5.64   9254  4596  4658   9429  50.47   7.78
2  2015  19469  4.20   9364  4714  4650  10105  51.91   7.17
3  2016  19456 -0.06   9620  4801  4819   9836  50.55  -2.67
4  2017  20493  5.33  10186  5042  5144  10225  49.90   3.96

In [16]:
origin.shape

(13, 9)

In [21]:
origin.columns.to_list()

['연도', ' 컨물동량', '증감율', '수출입소계', '수입', '수출', '환적소계', '환적점유율', '환적증감율']

In [22]:
origin.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연도      13 non-null     int64
 1    컨물동량   13 non-null     int64
 2   증감율     13 non-null     float64
 3   수출입소계   13 non-null     int64
 4   수입      13 non-null     int64
 5   수출      13 non-null     int64
 6   환적소계    13 non-null     int64
 7   환적점유율   13 non-null     float64
 8   환적증감율   13 non-null     float64
dtypes: float64(3), int64(6)
memory usage: 1.0 KB

In [25]:
origin.dtypes

연도         int64
 컨물동량      int64
증감율      float64
수출입소계      int64
수입         int64
수출         int64
환적소계       int64
환적점유율    float64
환적증감율    float64
dtype: object

In [26]:
# 결측치 확인
origin.isna().sum()

연도       0
 컨물동량    0
증감율      0
수출입소계    0
수입       0
수출       0
환적소계     0
환적점유율    0
환적증감율    0
dtype: int64

In [30]:
# 기술통계
origin.describe()

,연도,컨물동량,증감율,수출입소계,수입,수출,환적소계,환적점유율,환적증감율
count,13.00000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000
mean,2019.00000,21422.153846,2.991538,10071.230769,5014.000000,5057.076923,11343.846154,52.768462,4.395385
std,3.89444,2169.439707,2.770773,625.806966,310.466048,317.513638,1591.690864,2.233655,4.459913
min,2013.00000,17686.000000,-2.770000,8934.000000,4424.000000,4509.000000,8748.000000,49.470000,-4.130000
25%,2016.00000,19469.000000,1.520000,9620.000000,4801.000000,4819.000000,10105.000000,50.550000,2.100000
50%,2019.00000,21824.000000,4.040000,10233.000000,5117.000000,5144.000000,11638.000000,52.920000,4.400000
75%,2022.00000,22706.000000,5.330000,10433.000000,5208.000000,5225.000000,12273.000000,54.050000,7.380000
max,2025.00000,24882.000000,5.700000,10904.000000,5409.000000,5495.000000,14097.000000,56.700000,11.770000

## 분석흐름
1. 연도별 전체 물동량 확인
2. 연도별 환적소계 확인
3. 환적점유율의 변화 확인
4. 환적증감율과 전체 증감율 비교
5. 전체 성장분 중 환적 기여율 계산 (환적증감율)
6. 환적 중심 항만으로 성장했는지 결론 작성

+ 7. 영향 요인 분석 (선박크기, 체류시간, 피더 네트워크 규모, 주변국 물동량, 글로벌 교역량 또는 세계 컨테이너 물동량)

In [32]:
df=origin.copy()

In [ ]:
# 비교할 구성요소
df['전체물동량'] = df['수출입소계'] + df['환적소계']

      연도   컨물동량   증감율  수출입소계    수입    수출   환적소계  환적점유율  환적증감율  전체 물동량
0   2013  17686  3.75   8934  4424  4509   8748  49.47   7.38   17682
1   2014  18683  5.64   9254  4596  4658   9429  50.47   7.78   18683
2   2015  19469  4.20   9364  4714  4650  10105  51.91   7.17   19469
3   2016  19456 -0.06   9620  4801  4819   9836  50.55  -2.67   19456
4   2017  20493  5.33  10186  5042  5144  10225  49.90   3.96   20411
5   2018  21663  5.70  10233  5117  5116  11429  52.76  11.77   21662
6   2019  21992  1.52  10354  5192  5162  11638  52.92   1.83   21992
7   2020  21824 -0.76   9804  4853  4951  12020  55.08   3.28   21824
8   2021  22706  4.04  10433  5208  5225  12273  54.05   2.10   22706
9   2022  22078 -2.77  10311  5133  5178  11766  53.29  -4.13   22077
10  2023  23154  4.90  10744  5330  5413  12408  53.59   5.50   23152
11  2024  24402  5.40  10904  5409  5495  13496  55.30   8.77   24400
12  2025  24882  2.00  10785  5363  5422  14097  56.70   4.40   24882

# 인사이트
- 컨테이너 물동량이 감소한 연도: 2016, 2020, 2022
- 환적증감율이 감소한 연도: 2016, 2022
- 2020년 컨테이너 물동량이 감소했는데, 환적증감율은 증가했다. 왜 그럴까? 
코로나의 영향으로 수출입 물동량이 감소했을 것 같다. 하지만 환적 물동량은 증가했으니 부산항의 환적 네트워크와 운영 기능이 외부 충격 상황(코로나)에서 전체 물동량 감소를 일부 완화했을 것 같다. 
- 2014년부터 환적 비중이 전체 물동량에서 절반 이상으로 나타났다.